spring:
  application:
    name: chat-bot-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-oss-20b
          temperature: 0.7
